import sys

REQUIRED_PYTHON = "python3"


def main():
    system_major = sys.version_info.major
    if REQUIRED_PYTHON == "python":
        required_major = 2
    elif REQUIRED_PYTHON == "python3":
        required_major = 3
    else:
        raise ValueError("Unrecognized python interpreter: {}".format(
            REQUIRED_PYTHON))

    if system_major != required_major:
        raise TypeError(
            "This project requires Python {}. Found: Python {}".format(
                required_major, sys.version))
    else:
        print(">>> Development environment passes all tests!")


if __name__ == '__main__':
    main()


['Data Analyst (all genders)', '(Junior) Data Analyst (f/m/d)', 'Data Analyst', 'Junior Data Engineer (w/m/d)', 'Data Analyst (M/W/D)', '(Junior) Data Scientist / Analyst (m/f/d) - Remote', 'Data Scientist (F/M/X)', '(Junior) Data Analyst (w/m/d)', 'Data Analyst (Monetization)', 'Data Analyst (m/w/d)', 'Data Analyst (m/f/d)', 'Junior Expert Data Analytics / Visualization (m/w/d)', 'Data Analyst - Use Case Befähigung (w/m/x)', 'Data Analyst (f/m/x)', 'Data Analyst, Product', 'Internship - Data Analyst (m/f/x)', 'Data Analyst FI / CO (m/w/d)', 'Working Student Data Analytics (all genders)', 'Junior Manager Data Analytics & Planning (m/w/d)', 'Junior Associate, Data Management', 'Junior Consultant Data Analytics (m/w/d)', 'Clinical Data Scientist', 'Associate', 'Junior Data Engineer* / Junior Business Intelligence Consultant*', 'Working Student Data & BI (m/f/d)']
['(Junior) Data Analyst (f/m/d)', 'Data Analyst', 'Junior Data Engineer (w/m/d)', 'Data Analyst (M/W/D)', '(Junior) Data Scientist / Analyst (m/f/d) - Remote', 'Data Scientist (F/M/X)', '(Junior) Data Analyst (w/m/d)', 'Data Analyst (Monetization)', 'Data Analyst (m/w/d)', 'Data Analyst (m/f/d)', 'Junior Expert Data Analytics / Visualization (m/w/d)', 'Data Analyst - Use Case Befähigung (w/m/x)', 'Data Analyst (f/m/x)', 'Data Analyst, Product', 'Internship - Data Analyst (m/f/x)', 'Data Analyst FI / CO (m/w/d)', 'Working Student Data Analytics (all genders)', 'Junior Manager Data Analytics & Planning (m/w/d)', 'Junior Associate, Data Management', 'Junior Consultant Data Analytics (m/w/d)', 'Clinical Data Scientist', 'Associate', 'Junior Data Engineer* / Junior Business Intelligence Consultant*', 'Working Student Data & BI (m/f/d)', '(Senior) Business Intelligence Analyst (f/m/x)']
['Data Analyst', 'Junior Data Engineer (w/m/d)', 'Data Analyst (M/W/D)', '(Junior) Data Scientist / Analyst (m/f/d) - Remote', 'Data Scientist (F/M/X)', '(Junior) Data Analyst (w/m/d)', 'Data Analyst (Monetization)', 'Data Analyst (m/w/d)', 'Data Analyst (m/f/d)', 'Junior Expert Data Analytics / Visualization (m/w/d)', 'Data Analyst - Use Case Befähigung (w/m/x)', 'Data Analyst (f/m/x)', 'Data Analyst, Product', 'Internship - Data Analyst (m/f/x)', 'Data Analyst FI / CO (m/w/d)', 'Working Student Data Analytics (all genders)', 'Junior Manager Data Analytics & Planning (m/w/d)', 'Junior Associate, Data Management', 'Junior Consultant Data Analytics (m/w/d)', 'Clinical Data Scientist', 'Associate', 'Junior Data Engineer* / Junior Business Intelligence Consultant*', 'Working Student Data & BI (m/f/d)', '(Senior) Business Intelligence Analyst (f/m/x)', 'Data Scientist (f/m/d)']
['Junior Data Engineer (w/m/d)', 'Data Analyst (M/W/D)', '(Junior) Data Scientist / Analyst (m/f/d) - Remote', 'Data Scientist (F/M/X)', '(Junior) Data Analyst (w/m/d)', 'Data Analyst (Monetization)', 'Data Analyst (m/w/d)', 'Data Analyst (m/f/d)', 'Junior Expert Data Analytics / Visualization (m/w/d)', 'Data Analyst - Use Case Befähigung (w/m/x)', 'Data Analyst (f/m/x)', 'Data Analyst, Product', 'Internship - Data Analyst (m/f/x)', 'Data Analyst FI / CO (m/w/d)', 'Working Student Data Analytics (all genders)', 'Junior Manager Data Analytics & Planning (m/w/d)', 'Junior Associate, Data Management', 'Junior Consultant Data Analytics (m/w/d)', 'Clinical Data Scientist', 'Associate', 'Junior Data Engineer* / Junior Business Intelligence Consultant*', 'Working Student Data & BI (m/f/d)', '(Senior) Business Intelligence Analyst (f/m/x)', 'Data Scientist (f/m/d)', 'Data Engineer (m/w/d)']
['Data Analyst (M/W/D)', '(Junior) Data Scientist / Analyst (m/f/d) - Remote', 'Data Scientist (F/M/X)', '(Junior) Data Analyst (w/m/d)', 'Data Analyst (Monetization)', 'Data Analyst (m/w/d)', 'Data Analyst (m/f/d)', 'Junior Expert Data Analytics / Visualization (m/w/d)', 'Data Analyst - Use Case Befähigung (w/m/x)', 'Data Analyst (f/m/x)', 'Data Analyst, Product', 'Internship - Data Analyst (m/f/x)', 'Data Analyst FI / CO (m/w/d)', 'Working Student Data Analytics (all genders)', 'Junior Manager Data Analytics & Planning (m/w/d)', 'Junior Associate, Data Management', 'Junior Consultant Data Analytics (m/w/d)', 'Clinical Data Scientist', 'Associate', 'Junior Data Engineer* / Junior Business Intelligence Consultant*', 'Working Student Data & BI (m/f/d)', '(Senior) Business Intelligence Analyst (f/m/x)', 'Data Scientist (f/m/d)', 'Data Engineer (m/w/d)', 'Internship - Data Analysis / Research / Statistics (m/f/d)']
['(Junior) Data Scientist / Analyst (m/f/d) - Remote', 'Data Scientist (F/M/X)', '(Junior) Data Analyst (w/m/d)', 'Data Analyst (Monetization)', 'Data Analyst (m/w/d)', 'Data Analyst (m/f/d)', 'Junior Expert Data Analytics / Visualization (m/w/d)', 'Data Analyst - Use Case Befähigung (w/m/x)', 'Data Analyst (f/m/x)', 'Data Analyst, Product', 'Internship - Data Analyst (m/f/x)', 'Data Analyst FI / CO (m/w/d)', 'Working Student Data Analytics (all genders)', 'Junior Manager Data Analytics & Planning (m/w/d)', 'Junior Associate, Data Management', 'Junior Consultant Data Analytics (m/w/d)', 'Clinical Data Scientist', 'Associate', 'Junior Data Engineer* / Junior Business Intelligence Consultant*', 'Working Student Data & BI (m/f/d)', '(Senior) Business Intelligence Analyst (f/m/x)', 'Data Scientist (f/m/d)', 'Data Engineer (m/w/d)', 'Internship - Data Analysis / Research / Statistics (m/f/d)', 'Data Analyst Intern (m/f/d)']
['Data Scientist (F/M/X)', '(Junior) Data Analyst (w/m/d)', 'Data Analyst (Monetization)', 'Data Analyst (m/w/d)', 'Data Analyst (m/f/d)', 'Junior Expert Data Analytics / Visualization (m/w/d)', 'Data Analyst - Use Case Befähigung (w/m/x)', 'Data Analyst (f/m/x)', 'Data Analyst, Product', 'Internship - Data Analyst (m/f/x)', 'Data Analyst FI / CO (m/w/d)', 'Working Student Data Analytics (all genders)', 'Junior Manager Data Analytics & Planning (m/w/d)', 'Junior Associate, Data Management', 'Junior Consultant Data Analytics (m/w/d)', 'Clinical Data Scientist', 'Associate', 'Junior Data Engineer* / Junior Business Intelligence Consultant*', 'Working Student Data & BI (m/f/d)', '(Senior) Business Intelligence Analyst (f/m/x)', 'Data Scientist (f/m/d)', 'Data Engineer (m/w/d)', 'Internship - Data Analysis / Research / Statistics (m/f/d)', 'Data Analyst Intern (m/f/d)', 'Data Scientist']
['(Junior) Data Analyst (w/m/d)', 'Data Analyst (Monetization)', 'Data Analyst (m/w/d)', 'Data Analyst (m/f/d)', 'Junior Expert Data Analytics / Visualization (m/w/d)', 'Data Analyst - Use Case Befähigung (w/m/x)', 'Data Analyst (f/m/x)', 'Data Analyst, Product', 'Internship - Data Analyst (m/f/x)', 'Data Analyst FI / CO (m/w/d)', 'Working Student Data Analytics (all genders)', 'Junior Manager Data Analytics & Planning (m/w/d)', 'Junior Associate, Data Management', 'Junior Consultant Data Analytics (m/w/d)', 'Clinical Data Scientist', 'Associate', 'Junior Data Engineer* / Junior Business Intelligence Consultant*', 'Working Student Data & BI (m/f/d)', '(Senior) Business Intelligence Analyst (f/m/x)', 'Data Scientist (f/m/d)', 'Data Engineer (m/w/d)', 'Internship - Data Analysis / Research / Statistics (m/f/d)', 'Data Analyst Intern (m/f/d)', 'Data Scientist', 'Data Analyst (w/m/d)']
['Data Analyst (Monetization)', 'Data Analyst (m/w/d)', 'Data Analyst (m/f/d)', 'Junior Expert Data Analytics / Visualization (m/w/d)', 'Data Analyst - Use Case Befähigung (w/m/x)', 'Data Analyst (f/m/x)', 'Data Analyst, Product', 'Internship - Data Analyst (m/f/x)', 'Data Analyst FI / CO (m/w/d)', 'Working Student Data Analytics (all genders)', 'Junior Manager Data Analytics & Planning (m/w/d)', 'Junior Associate, Data Management', 'Junior Consultant Data Analytics (m/w/d)', 'Clinical Data Scientist', 'Associate', 'Junior Data Engineer* / Junior Business Intelligence Consultant*', 'Working Student Data & BI (m/f/d)', '(Senior) Business Intelligence Analyst (f/m/x)', 'Data Scientist (f/m/d)', 'Data Engineer (m/w/d)', 'Internship - Data Analysis / Research / Statistics (m/f/d)', 'Data Analyst Intern (m/f/d)', 'Data Scientist', 'Data Analyst (w/m/d)', 'Data Scientist (all genders)']
['Data Analyst (m/w/d)', 'Data Analyst (m/f/d)', 'Junior Expert Data Analytics / Visualization (m/w/d)', 'Data Analyst - Use Case Befähigung (w/m/x)', 'Data Analyst (f/m/x)', 'Data Analyst, Product', 'Internship - Data Analyst (m/f/x)', 'Data Analyst FI / CO (m/w/d)', 'Working Student Data Analytics (all genders)', 'Junior Manager Data Analytics & Planning (m/w/d)', 'Junior Associate, Data Management', 'Junior Consultant Data Analytics (m/w/d)', 'Clinical Data Scientist', 'Associate', 'Junior Data Engineer* / Junior Business Intelligence Consultant*', 'Working Student Data & BI (m/f/d)', '(Senior) Business Intelligence Analyst (f/m/x)', 'Data Scientist (f/m/d)', 'Data Engineer (m/w/d)', 'Internship - Data Analysis / Research / Statistics (m/f/d)', 'Data Analyst Intern (m/f/d)', 'Data Scientist', 'Data Analyst (w/m/d)', 'Data Scientist (all genders)', 'Junior-Data Engineer (m/w/d)']